on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v3

      - name: Check flake outputs
        run: nix flake check
