name: Build Recovery Media

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - system-module
    paths-ignore:
      - .github/**
      - assets/**
      - .gitignore

jobs:
    build-image:
		runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Install Cachix

			- uses: cachix/install-nix-action@v20
			  with:
				extra_nix_config: |
					access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}  github.com=${{ env.ACCESS_TOKEN}}
					auto-optimise-store = true
					experimental-features = nix-command flakes
				nix_path: nixpkgs=channel:nixos-unstable

			- name: Cachix setup
			  uses: cachix/cachix-action@v12
			  with:
				authToken: ${{ secrets.CACHIX_TOKEN }}
				extraPullNames: nix-community
				name: notashelf

            - uses: cachix/cachix-action@v12
              with:
                  name: notashelf
                  signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
            - run: nix flake check
            - run: nix build .#nixosConfigurations.gaea.config.system.build.toplevel
