name: Flake Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"

jobs:
  check:
    strategy:
      matrix:
        command:
          - nix flake check --accept-flake-config
          - nix run nixpkgs#alejandra -- -c .

    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: ${{ matrix.command }}
