name: Flake Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Check Flake
        run: nix flake check --accept-flake-config --all-systems
