name: Validate Flake Formatting

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/fmt.yml"
      - "!**.lock"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"
  push:
    paths:
      - "**.nix"
      - ".github/workflows/fmt.yml"
      - "!**.lock"
      - "!**.sh"
      - "!.editorconfig"
      - "!**.md"

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - run: nix run nixpkgs#alejandra -- -c .
