name: Validate Flake Formatting

on: [push, pull_request, workflow_dispatch]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - run: nix run nixpkgs#alejandra -- -c .
