name: "Serve Static Website"

on:
    workflow_dispatch:
    push:
        paths:
            - docs/**
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.20"

            - name: Get latest release
              id: get-release
              uses: actions/github-script@v4
              with:
                  script: |
                      const releases = await github.repos.listReleases({
                        owner: context.repo.owner,
                        repo: context.repo.repo
                      });

                      const latestRelease = releases.data[0].tag_name;
                      core.setOutput('release', latestRelease);

            - name: Download Go Binary
              run: |
                  curl -LO https://github.com/notashelf/docr/releases/latest/download/docr_*_linux_amd64.tar.gz
                  tar -xf docr_*_linux_amd64.tar.gz
                  chmod +x docr

            - name: Build Notes Page
              run: ./docr

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: output/
